# Generated by Django 3.2 on 2022-06-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='Book',
        ),
    ]
